### ISSUE TITLE
Add few ESLint errors (no-unused-vars) 

### ISSUE THREAD

**Issue by pdehaan** [gregglind/shield-studies-addon-utils#11]
If I try running ESLint (see config below), I get the following ESLint errors:

```sh
$ eslint .

/Users/pdehaan/dev/tmp/del/shield-studies-addon-utils/example/lib/variations.js
  10:5  error  'prefs' is defined but never used  no-unused-vars

/Users/pdehaan/dev/tmp/del/shield-studies-addon-utils/example/test/test-index.js
  1:5  error  'main' is defined but never used  no-unused-vars

/Users/pdehaan/dev/tmp/del/shield-studies-addon-utils/lib/index.js
    3:8  error  'Ci' is defined but never used  no-unused-vars
  104:2  error  Unnecessary semicolon           no-extra-semi

/Users/pdehaan/dev/tmp/del/shield-studies-addon-utils/test/test-xutils.js
  89:31  error  Parsing error: Unexpected token Boolean

✖ 5 problems (5 errors, 0 warnings)
```

### .eslintrc

```yaml
extends: eslint:recommended

env:
  es6: true
  node: true

rules:
  comma-dangle: 0
  no-console: 0
  no-unused-vars: [2, { vars: all, args: none }]
```

The line that ESLint really seems to be unable to parse is:
```js
const aConfig = xutils.xsetup(forSetup);
console.log(aConfig);
function hasVariationEffect() Boolean(prefSvc.get(FAKEPREF));
```

I think it doesn't like the lack of `{...}` around the function declaration and possibly the fact that we aren't returning a Boolean, just sort of converting something to a Boolean.

After converting that function to this:

```js
function hasVariationEffect() {
  return Boolean(prefSvc.get(FAKEPREF));
}
```

I get the following errors for that file:
```
/Users/pdehaan/dev/tmp/del/shield-studies-addon-utils/test/test-xutils.js
   39:4   error  Unnecessary semicolon             no-extra-semi
   54:9   error  'u' is defined but never used     no-unused-vars
  361:19  error  'seen' is defined but never used  no-unused-vars
```

**Comment by gregglind** [comment]
Thanks for digging into this!

**Comment by gregglind** [comment]
Any good advice about how to incorporate es lint into the build / ci process ?  make it part of test, I assume?

**Comment by pdehaan** [comment]
@gregglind You're already using Grunt and Travis-CI, so easiest ways would probably be one of:

a) Use **grunt-eslint** and have it run before/after `grunt test`.
b) Use **eslint** CLI and use a npm "pretest" (or "posttest") script which runs `eslint .` before `npm test` is run.

**Comment by pdehaan** [comment]
I opted for the **grunt-eslint** option in PR #12.
