### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by Osmose** [gregglind/shield-studies-addon-utils#15]
This repo could use a LICENSE file and comments in the appropriate files. It looks like it should be either MPLv2 or public domain.

**Comment by gregglind** [comment]
it's ISC, marked as such.  Claim: this is valid spdx format already.  See https://www.npmjs.com/package/shield-studies-addon-utils.  I am happy to mpl 2 instead with good reasons

**Comment by Osmose** [comment]
RE: the license, it's unusual to see a project that _only_ declares licensing information in `package.json` and nowhere else (I missed this the first time, hence my mistake). Also, the ISC license itself requires that copies include a copyright notice, so by definition any forks of this repo are automatically violating the license since they wouldn't include a `LICENSE` file with the notice. 

RE: Which license, prior to noticing that this isn't a Mozilla repo but is on your personal account, I suggested MPLv2 as it's what is suggested in the [licensing policy](https://www.mozilla.org/en-US/MPL/license-policy/). For stuff that's on your own account I dunno what the guidelines are. It depends on whether we consider this Mozilla-controlled code.

**Comment by gregglind** [comment]
fixed in #27
